import 'dart:convert';
import 'dart:math';
import 'package:consultation_app/constant/const_Api.dart';
import 'package:consultation_app/model/TagsModel.dart';
import 'package:consultation_app/model/userModel.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

class Auth extends ChangeNotifier {
  Autogenerated? token;
  User? user;
  Role? role;
  Map errorMessage = {};
  List<User> users = [];

  Future<bool> login(String _email, String _password) async {
    http.Response response = await http.post(Uri.parse(loginUrl), body: {
      'email': _email,
      'password': _password,
    });
    if (response.statusCode == 200) {
      var body = jsonDecode(response.body);
      user = User.fromJson(body['user']);
      token = Autogenerated.fromJson(body);
      role = Role.fromJson(body['user']['role']);
      notifyListeners();
      return true;
    } else {
      var body = jsonDecode(response.body);
      errorMessage = body;
      notifyListeners();
      return false;
    }
  }

  Future register(String email, String password, String username) async {
    http.Response response = await http.post(Uri.parse(registerUrl), body: {
      'password_confirmation': password,
      'email': email,
      'password': password,
      'name': username
    });
    if (response.statusCode == 200) {
      var body = jsonDecode(response.body);
      user = User.fromJson(body['user']);
      token = Autogenerated.fromJson(body);
      role = Role.fromJson(body['user']['role']);
      notifyListeners();
      return true;
    } else {
      var body = jsonDecode(response.body);
      errorMessage = body;
      notifyListeners();
      return false;
    }
    //   if (response.statusCode == 200) {
    //     var body = jsonDecode(response.body);
    //     User user = User.fromJson(body['user']);
    //     print('register email : ${user.email} , name : ${user.name}');
    //  }
  }

  Future getUser() async {
    http.Response response = await http.get(Uri.parse(userInfoUrl),
        headers: {'Authorization': 'Bearer ${token!.token!}'});
    if (response.statusCode == 200) {
      var body = jsonDecode(response.body);
      user = User.fromJson(body['user']);
      token = Autogenerated.fromJson(body);
      role = Role.fromJson(body['user']['role']);
      notifyListeners();
      return 'Success';
    } else {
      return 'error!!';
    }
  }

//remove

  Future updateUser(name) async {
    http.Response response = await http.put(
      Uri.parse(updateUserUrl(id: user!.id!, name: name)),
      headers: {'Authorization': 'Bearer ${token!.token!}'},
    );

    print(
        'Status code ${response.statusCode}  response from update :${response.body},');
  }

  Future logout() async {
    http.Response response = await http.post(Uri.parse(logoutUrl),
        headers: {'Authorization': 'Bearer ${token!.token!}'});
    if (response.statusCode == 200) {
      return 'Log out ${user!.name}';
    } else {
      return 'error!!';
    }
  }

  Future getAllUsers() async {
    http.Response response = await http.get(Uri.parse(allUsersUrl),
        headers: {'Authorization': 'Bearer ${token!.token!}'});
    if (response.statusCode == 200) {
      var body = jsonDecode(response.body);

      for (var user in body['users']) {
        user = User.fromJson(user);
        users.add(user);
      }
    } else {
      return 'error!!';
    }
  }

  Future createUser() async {
    http.Response response = await http.post(Uri.parse(allUsersUrl), headers: {
      'Authorization': 'Bearer ${token!.token!}'
    }, body: {
      'name': 'Som3a',
      'email': 'som3aa@gmail.com',
      'password': '123456',
      'password_confirmation': '123456',
      'role_id': '4'
    });
    print(
        'and status code : ${response.statusCode} ///// body : ${response.body} ');
  }

  Future getUserId(userId) async {
    http.Response response = await http.get(Uri.parse(getUserIdUrl(userId)),
        headers: {'Authorization': 'Bearer ${token!.token!}'});
    if (response.statusCode == 200) {
      var body = jsonDecode(response.body);
      user = User.fromJson(body);
      return user;
    } else {
      return 'error!!';
    }
  }

  Future deleteUser(userId) async {
    http.Response response = await http.delete(Uri.parse(deleteUserUrl(userId)),
        headers: {'Authorization': 'Bearer ${token!.token!}'});
    if (response.statusCode == 200) {
      var body = jsonDecode(response.body);
      user = User.fromJson(body);
      return 'Success Delete ${user!.name}';
    } else {
      return 'error!!';
    }
  }

  Future changePassword(password, userId) async {
    http.Response response = await http.post(
        Uri.parse(changePasswordUrl(userId)),
        headers: {'Authorization': 'Bearer ${token!.token!}'},
        body: {'password': password, 'password_confirmation': password});

    if (response.statusCode == 200) {
      return 'Succes change password';
    } else {
      return 'error';
    }
  }

  Future changeRole(roleId, UserId) async {
    http.Response response = await http.put(Uri.parse(changeRoleUrl(UserId)),
        headers: {'Authorization': 'Bearer ${token!.token!}'},
        body: {'role_id': roleId});
    if (response.statusCode == 200) {
      return 'Success';
    } else {
      return 'error!!';
    }
  }

  Future getallRoles() async {
    http.Response response = await http.get(
      Uri.parse(getRoleUrl),
      headers: {'Authorization': 'Bearer ${token!.token!}'},
    );
    print('roles ${response.body}');
  }

// pending
  Future Search(
      {String? statusId,
      required String text,
      String? start,
      String? end}) async {
    http.Response response = await http.get(
      Uri.parse(
          SearchUrl(text: text, statusId: statusId, start: start, end: end)),
      headers: {'Authorization': 'Bearer ${token!.token!}'},
    );
    print('hi search $statusId oo $text, $start, $end');
    print(response.body);
  }
}
